# Build runtime image.
FROM openjdk:18.0.2-jdk-slim
RUN apt update && apt install maven
EXPOSE 8080
RUN cd /app
COPY target/ /app/
# Starts java app with debugging server at port 8080.
CMD ["java", "-jar", "hello-world-1.0.0.jar"]
